language: java
jdk:
- openjdk11
services:
- mysql
branches:
  only:
  - main
before_install:
- openssl aes-256-cbc -K $encrypted_1116e8e6e492_key -iv $encrypted_1116e8e6e492_iv
  -in application.yml.enc -out application.yml -d
- chmod +x gradlew
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build --stacktrace"
notifications:
  email:
    recipients:
    - joungim.cho.chloe@gmail.com
    - rladlfgks422@gmail.com


before_deploy: # deploy 명령어가 실행되기 전에 수행
  - zip -r algoreview * # 현재 경로의 모든 파일을 algoreview.zip 파일로 압축
  - mkdir -p deploy
  - mv algoreview.zip deploy/algoreview.zip

deploy: # 외부 서비스와 연동될 행위들을 선언
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis CI의 Repository Environment Variable 설정 값
    secret_access_key: $AWS_SECRET_KEY # Travis CI의 Repository Environment Variable 설정 값
    bucket: algoreview-bucket # S3 버킷 이름
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근 private
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      all_branches: true